version: 2.1

orbs:
  node: circleci/node@7.1.0
  aws-cli: circleci/aws-cli@5.2.0

jobs:
  deploy:
    executor: 
      name: node/default
      tag: '22.13.1'
    steps:
      - checkout
      - node/install-packages:
          app-dir: infra
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          region: us-east-1
      - run:
          name: deploy
          command: |
            cd infra
            npm run deploy:dev -- --require-approval never

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                # - main
                - non-existent
